services:
  meilisearch:
    image: getmeili/meilisearch:v1.13
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: "masterKey"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/data.ms

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - meilisearch

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8001:8001"
    depends_on:
      - backend

volumes:
  meili_data: