services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "masterKey"  # Replace with your actual master key
      MEILI_DB_PATH: "postgres://user:password@postgres:5432/meilisearch"  # PostgreSQL connection string
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meilisearch
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Bind mount for PostgreSQL data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - meilisearch
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8001:8001"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: