services:
  meilisearch:
    image: getmeili/meilisearch:v1.13
    container_name: meilisearch
    environment:
      # Optional: Set a master key for secure access
      # For production, use environment variables
      - MEILI_MASTER_KEY=master_key
    ports:
      # Runs on port 7700 by default
      - "7700:7700"
    volumes:
      - meili_data:/data.ms
    restart: unless-stopped

  frontend:
    build: ./frontend  # Path to the Python frontend directory
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - meilisearch
    restart: unless-stopped

  nginx:
    image: nginx:mainline-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - meilisearch
      - frontend
    restart: unless-stopped

volumes:
  # Persist the MeiliSearch data
  meili_data: